# Generated by Django 2.1.4 on 2018-12-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_auto_20181219_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='products',
            field=models.ManyToManyField(blank=True, to='Ecommerce.Product'),
        ),
    ]
