# Generated by Django 2.1.4 on 2018-12-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_auto_20181219_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SCategroy',
            new_name='SCategory',
        ),
    ]
