# Generated by Django 2.1.4 on 2018-12-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0008_auto_20181219_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Image')),
            ],
        ),
        migrations.RenameModel(
            old_name='SCategory',
            new_name='SCategory1',
        ),
        migrations.AddField(
            model_name='scategory2',
            name='scategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.SCategory1'),
        ),
    ]
