# Generated by Django 2.1.4 on 2018-12-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_auto_20181219_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scategory1',
            field=models.ManyToManyField(blank=True, to='Ecommerce.SCategory2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='Ecommerce.Category'),
        ),
        migrations.AlterField(
            model_name='scategory2',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
