# Generated by Django 2.1.4 on 2018-12-19 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0010_auto_20181219_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
