# Generated by Django 2.1.4 on 2018-12-20 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0013_auto_20181220_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Color'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_sup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
