# Generated by Django 2.1.4 on 2018-12-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0015_auto_20181220_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price_sup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
