# Generated by Django 2.1.4 on 2018-12-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0019_auto_20181222_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scategory1',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
