# Generated by Django 2.1.4 on 2018-12-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0020_auto_20181222_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
