# Generated by Django 2.1.4 on 2018-12-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0021_auto_20181222_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
    ]
