# Generated by Django 2.1.4 on 2018-12-23 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0026_auto_20181223_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=100000),
        ),
    ]
