# Generated by Django 2.1.4 on 2018-12-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0027_auto_20181223_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='price_from',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
    ]
