# Generated by Django 2.1.4 on 2018-12-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0029_auto_20181223_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=650),
        ),
    ]
