# Generated by Django 2.1.4 on 2018-12-26 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0032_auto_20181226_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribe_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 22, 35, 59, 672068, tzinfo=utc)),
        ),
    ]
