# Generated by Django 2.1.4 on 2018-12-27 08:30

import Ecommerce.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0033_auto_20181226_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=Ecommerce.models.PathAndRename('images/2018/12/27')),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribe_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shoppings',
            field=models.ManyToManyField(blank=True, to='Ecommerce.Shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image_cover',
            field=models.ImageField(upload_to=Ecommerce.models.PathAndRename('images/2018/12/27')),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image_profile',
            field=models.ImageField(upload_to=Ecommerce.models.PathAndRename('images/2018/12/27')),
        ),
    ]
