# Generated by Django 2.1.4 on 2018-12-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0035_auto_20181227_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='stock',
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Color'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Product'),
        ),
    ]
