# Generated by Django 2.1.4 on 2018-12-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0038_auto_20181230_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shoppings',
        ),
    ]
