# Generated by Django 2.1.4 on 2018-12-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0039_auto_20181230_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=6000, unique=True),
        ),
    ]
