# Generated by Django 2.1.4 on 2019-01-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0041_auto_20190106_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesupplier',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='scategory1',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scategory1',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scategory2',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scategory2',
            name='scategory',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scategories1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='scategories2',
        ),
        migrations.DeleteModel(
            name='MessageSupplier',
        ),
        migrations.DeleteModel(
            name='SCategory1',
        ),
        migrations.DeleteModel(
            name='SCategory2',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
