# Generated by Django 2.1.4 on 2019-01-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0042_auto_20190106_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_approved',
        ),
    ]
