# Generated by Django 2.1.4 on 2019-01-12 19:19

import Ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0043_remove_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_min',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=Ecommerce.models.PathAndRename('images/2019/01/12')),
        ),
    ]
