# Generated by Django 2.1.4 on 2019-01-29 14:44

import Ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0048_auto_20190126_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'Cash On Delivery'), ('2', 'Paypal')], default='Cash On Delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=Ecommerce.models.PathAndRename('images/2019/01/29')),
        ),
    ]
