# Generated by Django 2.1.4 on 2019-01-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0049_auto_20190129_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Free Shipping', 'Free Shipping'), ('Flat Shipping Rate', 'Flat Shipping Rate')], default='Free Shipping', max_length=20),
        ),
    ]
