# Generated by Django 2.1.4 on 2019-01-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0051_auto_20190129_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='post_code',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='region',
            new_name='zipcode',
        ),
    ]
