# Generated by Django 2.1.4 on 2019-01-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0052_auto_20190129_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortDescription',
            new_name='Specification',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(max_length=254),
        ),
    ]
