# Generated by Django 2.1.4 on 2019-02-03 22:27

import Ecommerce.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0054_auto_20190129_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_email_expiration',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=Ecommerce.models.PathAndRename('images/2019/02/03')),
        ),
    ]
