# Generated by Django 2.1.4 on 2019-02-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0055_auto_20190203_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_email',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token_email_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
